version: '3.8'

services:
  # PostgreSQL Database (Production)
  postgres:
    image: postgres:15-alpine
    container_name: rpa_postgres_prod
    environment:
      POSTGRES_DB: rpa_bots
      POSTGRES_USER: rpa_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - rpa_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpa_user -d rpa_bots"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis Cache/Queue (Production)
  redis:
    image: redis:7-alpine
    container_name: rpa_redis_prod
    command: redis-server --appendonly yes
    volumes:
      - redis_prod_data:/data
    networks:
      - rpa_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Backend API (Production)
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: rpa_backend_prod
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://rpa_user:${POSTGRES_PASSWORD}@postgres:5432/rpa_bots
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rpa_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Celery Worker (Production)
  celery_worker:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: rpa_celery_worker_prod
    command: celery -A app.core.celery_app worker --loglevel=info
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://rpa_user:${POSTGRES_PASSWORD}@postgres:5432/rpa_bots
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rpa_network
    restart: unless-stopped

  # Celery Beat (Production)
  celery_beat:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: rpa_celery_beat_prod
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://rpa_user:${POSTGRES_PASSWORD}@postgres:5432/rpa_bots
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rpa_network
    restart: unless-stopped

volumes:
  postgres_prod_data:
    driver: local
  redis_prod_data:
    driver: local

networks:
  rpa_network:
    driver: bridge 